#!/usr/bin/env python3
"""Generate tests/wmm_reference.h: magnetic declination and inclination from
the official World Magnetic Model WMM2025 (NOAA/NGA, public domain) for
reference points, used by test_earth_induction_model.cpp.

Reference points:
  - five points in every area of NAV_Algorithms/earth_induction_model.cpp
    (centre and four points 15 % inside the corners), read from that file;
  - well-known soaring sites on all continents, which the model is expected
    to cover.

Requires: pip install pygeomag  (ships the WMM2025 coefficients)
Usage:    python3 tests/tools/make_wmm_reference.py > tests/wmm_reference.h
"""

import re
import sys
from pathlib import Path

from pygeomag import GeoMag

EPOCH = 2026.75      # decimal year the reference values are computed for
ALTITUDE_KM = 0.5    # typical airfield / flight altitude

SOARING_SITES = [
    # name, latitude, longitude
    ("Luesse DE", 52.14, 12.66),
    ("St. Auban FR", 44.06, 5.99),
    ("Ontur ES", 38.62, -1.53),
    ("Rieti IT", 42.43, 12.85),
    ("Leszno PL", 51.83, 16.52),
    ("Moscow RU", 55.75, 37.62),
    ("Bitterwasser NA", -23.87, 17.99),
    ("Kuruman ZA", -27.46, 23.43),
    ("Benalla AU", -36.55, 145.99),
    ("Narromine AU", -32.23, 148.23),
    ("Omarama NZ", -44.49, 169.97),
    ("Minden NV US", 38.95, -119.77),
    ("Uvalde TX US", 29.21, -99.74),
    ("Santiago CL", -33.39, -70.58),
    ("Bariloche AR", -41.13, -71.30),
    ("Itakura JP", 36.22, 139.61),
]


def model_areas(source):
    """(name, left, right, bottom, top) for every area in earth_induction_model.cpp"""
    pattern = re.compile(
        r"\{\s*//\s*([^\n]+)\n\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*//\s*left, right\s*\n"
        r"\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,")
    for match in pattern.finditer(source):
        yield (match.group(1).strip(), *map(float, match.groups()[1:]))


def main():
    root = Path(__file__).resolve().parents[2]
    source = (root / "NAV_Algorithms" / "earth_induction_model.cpp").read_text()
    geomag = GeoMag(coefficients_file="wmm/WMM_2025.COF")

    def line(name, latitude, longitude):
        field = geomag.calculate(glat=latitude, glon=longitude, alt=ALTITUDE_KM, time=EPOCH)
        return f'  {{ "{name}", {latitude:.2f}, {longitude:.2f}, {field.d:.2f}, {field.i:.2f} }},'

    out = [
        "// Generated by tests/tools/make_wmm_reference.py - do not edit.",
        f"// WMM2025 declination / inclination in degrees, epoch {EPOCH}, altitude {ALTITUDE_KM} km.",
        "#ifndef WMM_REFERENCE_H_",
        "#define WMM_REFERENCE_H_",
        "",
        "struct wmm_reference_t { const char *name; double latitude, longitude, declination, inclination; };",
        "",
        "// five points in every area of earth_induction_model.cpp",
        "static const wmm_reference_t WMM_AREA_POINTS[] = {",
    ]
    for name, left, right, bottom, top in model_areas(source):
        dx, dy = (right - left) * 0.15, (top - bottom) * 0.15
        for latitude, longitude in [((bottom + top) / 2, (left + right) / 2),
                                    (bottom + dy, left + dx), (bottom + dy, right - dx),
                                    (top - dy, left + dx), (top - dy, right - dx)]:
            out.append(line(name, latitude, longitude))
    out += ["};", "", "// soaring sites the model has to cover", "static const wmm_reference_t WMM_SOARING_SITES[] = {"]
    out += [line(name, latitude, longitude) for name, latitude, longitude in SOARING_SITES]
    out += ["};", "", "#endif /* WMM_REFERENCE_H_ */", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
