// Tests for the earth magnetic field model (earth_induction_model.cpp) and
// how the AHRS uses it (larus-breeze/sw_algorithms_lib#154).
//
// Reference values come from the official World Magnetic Model WMM2025,
// generated by tests/tools/make_wmm_reference.py into wmm_reference.h.
//
// Built without exceptions (like the firmware): REQUIRE does not abort a test
// case, so checks that later ones depend on use CHECK plus an explicit return.
//
// Known defects are test cases decorated with doctest::should_fail(): they
// pass while the defect exists and fail once it is fixed, so the fix has to
// remove the decorator and the test case guards it from then on.

#include <string.h>
#include <math.h>

#include "doctest.h"
#include "wmm_reference.h"
#include "earth_induction_model.h"
#include "AHRS.h"

// The regional fits stay within about 2.7 degrees of WMM2025 in 2026.
// 3 degrees still separates "right" from "wrong" (the New Zealand
// inclination is 80-97 degrees off) and leaves room for the secular
// variation the fits do not contain.
static const double TOLERANCE_DEG = 3.0;

static bool named( const wmm_reference_t &p, const char *name)
{
  return strcmp( p.name, name) == 0;
}

static bool in_new_zealand( const wmm_reference_t &p)
{
  return named( p, "new zealand") || named( p, "Omarama NZ");
}

// soaring sites outside all areas of the current model (#154)
static bool uncovered_site( const wmm_reference_t &p)
{
  return named( p, "Moscow RU") || named( p, "Bariloche AR") || named( p, "Itakura JP");
}

// get_induction_data_at takes (latitude, longitude), as defined in the .cpp and used by organizer.h
static induction_values model_at( const wmm_reference_t &p)
{
  earth_induction_model_t model;
  return model.get_induction_data_at( p.latitude, p.longitude);
}

static void check_declination( const wmm_reference_t &p, const induction_values &v)
{
  CAPTURE( p.name); CAPTURE( p.latitude); CAPTURE( p.longitude); CAPTURE( p.declination); CAPTURE( v.declination);
  CHECK( fabs( v.declination - p.declination) <= TOLERANCE_DEG);
}

static void check_inclination( const wmm_reference_t &p, const induction_values &v)
{
  CAPTURE( p.name); CAPTURE( p.latitude); CAPTURE( p.longitude); CAPTURE( p.inclination); CAPTURE( v.inclination);
  CHECK( fabs( v.inclination - p.inclination) <= TOLERANCE_DEG);
}

// ---- values against WMM2025 --------------------------------------------------

TEST_CASE( "earth model: every area matches WMM2025")
{
  for( const wmm_reference_t &p : WMM_AREA_POINTS)
    {
      induction_values v = model_at( p);
      CAPTURE( p.name); CAPTURE( p.latitude); CAPTURE( p.longitude);
      CHECK( v.valid);
      if( ! v.valid)
	continue;
      check_declination( p, v);
      if( ! in_new_zealand( p))
	check_inclination( p, v);
    }
}

TEST_CASE( "earth model: soaring sites are covered and match WMM2025")
{
  for( const wmm_reference_t &p : WMM_SOARING_SITES)
    {
      if( uncovered_site( p))
	continue;
      induction_values v = model_at( p);
      CAPTURE( p.name);
      CHECK( v.valid);
      if( ! v.valid)
	continue;
      check_declination( p, v);
      if( ! in_new_zealand( p))
	check_inclination( p, v);
    }
}

TEST_CASE( "earth model: New Zealand inclination matches WMM2025"
	   * doctest::should_fail() * doctest::description( "known issue #154"))
{
  for( const wmm_reference_t &p : WMM_AREA_POINTS)
    if( in_new_zealand( p))
      check_inclination( p, model_at( p));
  for( const wmm_reference_t &p : WMM_SOARING_SITES)
    if( in_new_zealand( p))
      check_inclination( p, model_at( p));
}

static void check_site_covered( const char *name)
{
  for( const wmm_reference_t &p : WMM_SOARING_SITES)
    if( named( p, name))
      {
	CAPTURE( p.name);
	CHECK( model_at( p).valid);
	return;
      }
  FAIL( "site not in wmm_reference.h: " << name);
}

TEST_CASE( "earth model: covers Moscow" * doctest::should_fail() * doctest::description( "known issue #154"))
{
  check_site_covered( "Moscow RU");
}

TEST_CASE( "earth model: covers Itakura (Japan)" * doctest::should_fail() * doctest::description( "known issue #154"))
{
  check_site_covered( "Itakura JP");
}

TEST_CASE( "earth model: covers Bariloche (Argentina)" * doctest::should_fail() * doctest::description( "known issue #154"))
{
  check_site_covered( "Bariloche AR");
}

// ---- physical plausibility wherever the model claims to be valid -----------

static bool in_new_zealand_area( double latitude, double longitude)
{
  return longitude >= 165.0 && longitude <= 179.0 && latitude >= -48.0 && latitude <= -34.0;
}

// cells (lat -60..70, 1 degree) with an implausible value, inside or outside New Zealand
static unsigned implausible_cells( bool new_zealand)
{
  earth_induction_model_t model;
  unsigned count = 0;
  for( int latitude = -60; latitude < 70; ++latitude)
    for( int longitude = -180; longitude < 180; ++longitude)
      {
	double la = latitude + 0.5, lo = longitude + 0.5;
	if( in_new_zealand_area( la, lo) != new_zealand)
	  continue;
	induction_values v = model.get_induction_data_at( la, lo);
	if( ! v.valid)
	  continue;
	// near the magnetic poles the declination reaches large values, so only the range is checked
	bool out_of_range = ! ( fabs( v.declination) <= 180.0 && fabs( v.inclination) <= 90.0);
	// away from the magnetic equator the field points down in the north and up in the south
	bool wrong_sign = fabs( la) >= 25.0 && ( ( la > 0.0) != ( v.inclination > 0.0));
	if( out_of_range || wrong_sign)
	  ++count;
      }
  return count;
}

TEST_CASE( "earth model: plausible values and inclination sign outside New Zealand")
{
  CHECK( implausible_cells( false) == 0);
}

TEST_CASE( "earth model: plausible values and inclination sign in New Zealand"
	   * doctest::should_fail() * doctest::description( "known issue #154"))
{
  CHECK( implausible_cells( true) == 0);
}

// ---- the expected field in the AHRS -----------------------------------------------

static const double DECLINATIONS[] = { 4.4, -14.4, 25.0 };
static const double INCLINATIONS[] = { 64.4, -63.9, -69.8 };

TEST_CASE( "AHRS: expected induction east and down components")
{
  for( double d : DECLINATIONS)
    for( double i : INCLINATIONS)
      {
	CAPTURE( d); CAPTURE( i);
	AHRS_type ahrs( 0.01f);
	ahrs.update_magnetic_induction_data( (float)d, (float)i);
	const float3vector &e = ahrs.get_expected_nav_induction();
	double dr = d * M_PI / 180.0, ir = i * M_PI / 180.0;
	CHECK( fabs( e[EAST] - cos( ir) * sin( dr)) < 1e-3);
	CHECK( fabs( e[DOWN] - sin( ir)) < 1e-3);
      }
}

TEST_CASE( "AHRS: expected induction without declination is a unit vector")
{
  for( double i : INCLINATIONS)
    {
      CAPTURE( i);
      AHRS_type ahrs( 0.01f);
      ahrs.update_magnetic_induction_data( 0.0f, (float)i);
      const float3vector &e = ahrs.get_expected_nav_induction();
      CHECK( fabs( e[NORTH] - cos( i * M_PI / 180.0)) < 1e-3);
      CHECK( fabs( e.abs() - 1.0) < 1e-3);
    }
}

TEST_CASE( "AHRS: expected induction north = cos(incl)*cos(decl), unit length"
	   * doctest::should_fail() * doctest::description( "known issue: cos(declination) missing in AHRS.h:73"))
{
  for( double d : DECLINATIONS)
    for( double i : INCLINATIONS)
      {
	CAPTURE( d); CAPTURE( i);
	AHRS_type ahrs( 0.01f);
	ahrs.update_magnetic_induction_data( (float)d, (float)i);
	const float3vector &e = ahrs.get_expected_nav_induction();
	CHECK( fabs( e[NORTH] - cos( i * M_PI / 180.0) * cos( d * M_PI / 180.0)) < 1e-3);
	CHECK( fabs( e.abs() - 1.0) < 1e-3);
      }
}

TEST_CASE( "AHRS: does not run with a zero expected field"
	   * doctest::should_fail() * doctest::description( "known issue: zero expected field until the first GNSS fix"))
{
  // A freshly constructed AHRS keeps the zero vector until organizer.h feeds it
  // model data for a GNSS position (and, before #154 is fixed, forever outside
  // the model's areas): no magnetic heading aiding, permanent disturbance flag.
  AHRS_type ahrs( 0.01f);
  CHECK( ahrs.get_expected_nav_induction().abs() > 0.5f);
}
