// Tests for the earth magnetic field model (earth_induction_model.cpp) and
// how the AHRS uses it (larus-breeze/sw_algorithms_lib#154).
//
// Reference values come from the official World Magnetic Model WMM2025,
// generated by tests/tools/make_wmm_reference.py into wmm_reference.h.

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

#include "check.h"
#include "wmm_reference.h"
#include "earth_induction_model.h"
#include "AHRS.h"
#include "compass_calibrator_3D.h"
#include "abstract_EEPROM_storage.h"

// ---- environment stubs (AHRS and compass calibrator link against these) ----
float configuration( EEPROM_PARAMETER_ID id)
{
  return id == ANT_BASELENGTH ? 1.0f : 0.0f;
}
EEPROM_file_system<LOWEST_UNUSED_EEPROM_ID> permanent_data_file;
void FLASH_write( uint32_t *, uint32_t *, unsigned, bool) {}
magnetic_calculation_data_t temporary_mag_calculation_data;
compass_calibrator_3D_t compass_calibrator_3D( temporary_mag_calculation_data);
compass_calibrator_3D_t external_compass_calibrator_3D( temporary_mag_calculation_data);
void trigger_compass_calibrator_3D_calculation( bool) {}

// The regional fits stay within about 2.7 degrees of WMM2025 in 2026.
// 3 degrees still separates "right" from "wrong" (the New Zealand
// inclination is 80-97 degrees off) and leaves room for the secular
// variation the fits do not contain.
static const double TOLERANCE_DEG = 3.0;

static char text[160];

static bool is_new_zealand( const wmm_reference_t &p)
{
  return strcmp( p.name, "new zealand") == 0 || strcmp( p.name, "Omarama NZ") == 0;
}

// sites outside all areas of the current model (#154)
static bool is_uncovered_site( const wmm_reference_t &p)
{
  return strcmp( p.name, "Moscow RU") == 0 || strcmp( p.name, "Bariloche AR") == 0
      || strcmp( p.name, "Itakura JP") == 0;
}

static void compare_with_reference( earth_induction_model_t &model, const wmm_reference_t &p)
{
  // get_induction_data_at takes (latitude, longitude), as defined in the .cpp and used by organizer.h
  induction_values v = model.get_induction_data_at( p.latitude, p.longitude);

  snprintf( text, sizeof text, "%s (%.2f, %.2f): model covers this place", p.name, p.latitude, p.longitude);
  if( is_uncovered_site( p))
    {
      check_known_issue( v.valid, text, "#154");
      return;
    }
  check( v.valid, text);
  if( ! v.valid)
    return;

  snprintf( text, sizeof text, "%s (%.2f, %.2f): declination %.2f vs WMM2025 %.2f",
	    p.name, p.latitude, p.longitude, v.declination, p.declination);
  check( fabs( v.declination - p.declination) <= TOLERANCE_DEG, text);

  snprintf( text, sizeof text, "%s (%.2f, %.2f): inclination %.2f vs WMM2025 %.2f",
	    p.name, p.latitude, p.longitude, v.inclination, p.inclination);
  if( is_new_zealand( p))
    check_known_issue( fabs( v.inclination - p.inclination) <= TOLERANCE_DEG, text, "#154");
  else
    check( fabs( v.inclination - p.inclination) <= TOLERANCE_DEG, text);
}

//! values against WMM2025 in every area and at the soaring sites
static void test_reference_values( void)
{
  earth_induction_model_t model;
  for( const wmm_reference_t &p : WMM_AREA_POINTS)
    compare_with_reference( model, p);
  for( const wmm_reference_t &p : WMM_SOARING_SITES)
    compare_with_reference( model, p);
}

//! physical plausibility wherever the model claims to be valid
static void test_plausibility( void)
{
  earth_induction_model_t model;
  unsigned covered = 0, out_of_range = 0, wrong_sign = 0, wrong_sign_nz = 0;
  for( int latitude = -60; latitude < 70; ++latitude)
    for( int longitude = -180; longitude < 180; ++longitude)
      {
	double la = latitude + 0.5, lo = longitude + 0.5;
	induction_values v = model.get_induction_data_at( la, lo);
	if( ! v.valid)
	  continue;
	++covered;
	if( ! ( fabs( v.declination) <= 60.0 && fabs( v.inclination) <= 90.0))
	  ++out_of_range;
	// away from the magnetic equator the field points down in the north and up in the south
	if( fabs( la) >= 25.0 && ( ( la > 0.0) != ( v.inclination > 0.0)))
	  {
	    if( lo >= 165.0 && lo <= 179.0 && la >= -48.0 && la <= -34.0)
	      ++wrong_sign_nz;
	    else
	      ++wrong_sign;
	  }
      }
  snprintf( text, sizeof text, "plausibility: %u covered cells, none with |declination| > 60 or |inclination| > 90", covered);
  check( out_of_range == 0, text);
  snprintf( text, sizeof text, "plausibility: inclination sign matches the hemisphere outside New Zealand (%u cells wrong)", wrong_sign);
  check( wrong_sign == 0, text);
  snprintf( text, sizeof text, "plausibility: inclination sign matches the hemisphere in New Zealand (%u cells wrong)", wrong_sign_nz);
  check_known_issue( wrong_sign_nz == 0, text, "#154");
}

//! the expected field the AHRS derives from declination and inclination must be a unit vector
static void test_ahrs_expected_induction( void)
{
  const double declinations[] = { 0.0, 4.4, -14.4, 25.0 };
  const double inclinations[] = { 64.4, -63.9, -69.8 };
  for( double d : declinations)
    for( double i : inclinations)
      {
	AHRS_type ahrs( 0.01f);
	ahrs.update_magnetic_induction_data( (float)d, (float)i);
	const float3vector &e = ahrs.get_expected_nav_induction();
	double dr = d * M_PI / 180.0, ir = i * M_PI / 180.0;
	double north = cos( ir) * cos( dr), east = cos( ir) * sin( dr), down = sin( ir);

	snprintf( text, sizeof text, "AHRS expected induction (decl %.1f, incl %.1f): east and down components", d, i);
	check( fabs( e[EAST] - east) < 1e-3 && fabs( e[DOWN] - down) < 1e-3, text);

	snprintf( text, sizeof text, "AHRS expected induction (decl %.1f, incl %.1f): north = cos(incl)*cos(decl), unit length", d, i);
	bool north_ok = fabs( e[NORTH] - north) < 1e-3 && fabs( e.abs() - 1.0) < 1e-3;
	if( d == 0.0)
	  check( north_ok, text); // without declination the missing cos(decl) does not matter
	else
	  check_known_issue( north_ok, text, "AHRS.h:73 cos(declination) missing");
      }
}

//! the AHRS must not run with the zero vector as expected field
static void test_ahrs_never_uses_zero_field( void)
{
  // A freshly constructed AHRS, and one whose location is outside the model
  // (organizer.h only updates it for valid model data), keeps the zero vector:
  // no magnetic heading aiding and a permanent disturbance flag.
  AHRS_type ahrs( 0.01f);
  check_known_issue( ahrs.get_expected_nav_induction().abs() > 0.5f,
		     "AHRS without model data has a non-zero expected field (or a fallback)", "#154");
}

int main( void)
{
  test_reference_values();
  test_plausibility();
  test_ahrs_expected_induction();
  test_ahrs_never_uses_zero_field();
  return test_summary();
}
