// Generated by tests/tools/make_wmm_reference.py - do not edit.
// WMM2025 declination / inclination in degrees, epoch 2026.75, altitude 0.5 km.
#ifndef WMM_REFERENCE_H_
#define WMM_REFERENCE_H_

struct wmm_reference_t { const char *name; double latitude, longitude, declination, inclination; };

// five points in every area of earth_induction_model.cpp
static const wmm_reference_t WMM_AREA_POINTS[] = {
  { "DACH", 50.00, 11.00, 4.35, 65.97 },
  { "DACH", 46.85, 6.80, 3.22, 62.90 },
  { "DACH", 46.85, 15.20, 4.98, 63.54 },
  { "DACH", 53.15, 6.80, 3.33, 68.21 },
  { "DACH", 53.15, 15.20, 5.73, 68.68 },
  { "europe", 47.50, 7.50, 3.40, 63.55 },
  { "europe", 31.75, -8.25, -0.73, 42.44 },
  { "europe", 31.75, 23.25, 4.48, 46.29 },
  { "europe", 63.25, -8.25, -3.77, 74.58 },
  { "europe", 63.25, 23.25, 10.97, 75.33 },
  { "africa", 2.50, 20.00, 1.66, -20.31 },
  { "africa", -23.75, -8.00, -20.51, -63.89 },
  { "africa", -23.75, 48.00, -22.95, -56.71 },
  { "africa", 28.75, -8.00, -0.82, 37.26 },
  { "africa", 28.75, 48.00, 3.62, 45.22 },
  { "australia", -25.00, 132.50, 4.13, -56.92 },
  { "australia", -35.50, 116.75, -2.45, -69.21 },
  { "australia", -35.50, 148.25, 12.39, -66.29 },
  { "australia", -14.50, 116.75, 1.01, -42.87 },
  { "australia", -14.50, 148.25, 6.74, -41.52 },
  { "usa", 47.50, -97.50, 3.03, 72.41 },
  { "usa", 31.75, -116.75, 10.60, 56.95 },
  { "usa", 31.75, -78.25, -9.15, 58.94 },
  { "usa", 63.25, -116.75, 16.56, 80.33 },
  { "usa", 63.25, -78.25, -19.01, 81.24 },
  { "south america", -20.00, -57.50, -17.22, -26.91 },
  { "south america", -34.00, -73.25, 2.84, -35.52 },
  { "south america", -34.00, -41.75, -20.03, -51.47 },
  { "south america", -6.00, -73.25, -8.03, 8.21 },
  { "south america", -6.00, -41.75, -21.35, -23.08 },
  { "new zealand", -41.00, 172.00, 22.65, -66.79 },
  { "new zealand", -45.90, 167.10, 25.71, -71.37 },
  { "new zealand", -45.90, 176.90, 27.36, -69.42 },
  { "new zealand", -36.10, 167.10, 18.57, -63.68 },
  { "new zealand", -36.10, 176.90, 20.15, -61.71 },
  { "iceland", 64.50, -18.50, -9.39, 75.51 },
  { "iceland", 62.75, -24.45, -11.81, 74.66 },
  { "iceland", 62.75, -12.55, -5.84, 74.31 },
  { "iceland", 66.25, -24.45, -13.14, 76.79 },
  { "iceland", 66.25, -12.55, -6.67, 76.39 },
};

// soaring sites the model has to cover
static const wmm_reference_t WMM_SOARING_SITES[] = {
  { "Luesse DE", 52.14, 12.66, 4.94, 67.77 },
  { "St. Auban FR", 44.06, 5.99, 2.97, 60.07 },
  { "Ontur ES", 38.62, -1.53, 1.20, 53.07 },
  { "Rieti IT", 42.43, 12.85, 4.17, 58.94 },
  { "Leszno PL", 51.83, 16.52, 5.89, 67.77 },
  { "Moscow RU", 55.75, 37.62, 12.14, 71.74 },
  { "Bitterwasser NA", -23.87, 17.99, -14.39, -63.91 },
  { "Kuruman ZA", -27.46, 23.43, -20.95, -63.57 },
  { "Benalla AU", -36.55, 145.99, 11.89, -67.52 },
  { "Narromine AU", -32.23, 148.23, 11.13, -63.24 },
  { "Omarama NZ", -44.49, 169.97, 25.05, -69.80 },
  { "Minden NV US", 38.95, -119.77, 12.60, 62.55 },
  { "Uvalde TX US", 29.21, -99.74, 4.13, 57.42 },
  { "Santiago CL", -33.39, -70.58, -0.00, -35.32 },
  { "Bariloche AR", -41.13, -71.30, 5.51, -42.18 },
  { "Itakura JP", 36.22, 139.61, -8.12, 50.25 },
};

#endif /* WMM_REFERENCE_H_ */
