#ifndef SIGNAL_FLIGHT_EVENT_H_
#define SIGNAL_FLIGHT_EVENT_H_

#include "FreeRTOS_wrapper.h"

enum event
{
  NO_EVENT,

  MAG_CALIBRATION_DONE,
  EXT_MAG_CALIBRATION_DONE,
  AIR_DENSITY_MODIFIED,

  EEPROM_CONFIGURATION_CHANGED,
  CAN_COMMAND_RECEIVED
};

void signal_logger_event( uint32_t event);

#endif /* SIGNAL_FLIGHT_EVENT_H_ */
