#ifndef COMMUNICATOR_COMMAND_H_
#define COMMUNICATOR_COMMAND_H_

typedef enum
{
  NO_COMMAND,
  MEASURE_CALIB_LEFT,
  MEASURE_CALIB_RIGHT,
  MEASURE_CALIB_LEVEL,
  SET_SENSOR_ROTATION,
  FINE_TUNE_CALIB,
  TIME_CONSTANT_CHANGED,
  TUNE_PRESSURE_GAUGES,
  GNSS_CONFIG_CHANGED
} communicator_command_t;

#endif /* COMMUNICATOR_COMMAND_H_ */
