#!/usr/bin/env python3
"""Generate NAV_Algorithms/wmm_coefficients.h from a World Magnetic Model
coefficient file (WMM.COF, NOAA/NGA, public domain).

Usage (from the repository root):
    python3 World_Magnetic_Model_design/make_wmm_coefficients.py \
        World_Magnetic_Model_design/WMM.COF > NAV_Algorithms/wmm_coefficients.h

When a new model is published (every five years, next WMM2030), replace
WMM.COF with the new file from https://www.ncei.noaa.gov/products/world-magnetic-model
and rerun this script.
"""

import sys


def main():
    lines = open(sys.argv[1]).read().splitlines()
    epoch, name, date = lines[0].split()[:3]
    rows = []
    for line in lines[1:]:
        fields = line.split()
        if len(fields) < 6 or fields[0].startswith("9999"):
            break
        n, m = int(fields[0]), int(fields[1])
        g, h, dg, dh = map(float, fields[2:6])
        rows.append((n, m, g, h, dg, dh))
    degree = max(n for n, *_ in rows)
    expected = [(n, m) for n in range(1, degree + 1) for m in range(n + 1)]
    if [(n, m) for n, m, *_ in rows] != expected:
        sys.exit("unexpected coefficient order in " + sys.argv[1])

    out = [
        "// Generated by World_Magnetic_Model_design/make_wmm_coefficients.py - do not edit.",
        f"// Source: {name} ({date}), NOAA/NGA World Magnetic Model, public domain.",
        "#ifndef NAV_ALGORITHMS_WMM_COEFFICIENTS_H_",
        "#define NAV_ALGORITHMS_WMM_COEFFICIENTS_H_",
        "",
        f"#define WMM_EPOCH  {float(epoch):.1f}  //!< epoch of the coefficients, decimal year",
        f"#define WMM_DEGREE {degree}      //!< maximum spherical harmonic degree",
        "",
        "//! Gauss coefficients in nT and their secular variation in nT/year,",
        "//! ordered n = 1..WMM_DEGREE, m = 0..n",
        "struct wmm_coefficient_t { float g, h, dg, dh; };",
        "",
        "static ROM wmm_coefficient_t WMM_COEFFICIENTS[] =",
        "{",
    ]
    for n, m, g, h, dg, dh in rows:
        out.append(f"  {{ {g:9.1f}f, {h:9.1f}f, {dg:6.1f}f, {dh:6.1f}f }}, // n={n:2d} m={m:2d}")
    out += ["};", "", "#endif /* NAV_ALGORITHMS_WMM_COEFFICIENTS_H_ */", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
